<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="tvmatp2261m.ad.infosys.com" name="Default test" tests="3" failures="2" timestamp="1 Jun 2016 12:47:41 GMT" time="664.606" errors="0">
  <testcase name="SubmitOrder_Categories_Home" time="264.978" classname="com.tests.May27TestSuite4"/>
  <testcase name="SubmitOrder_Categories_Search_Home" time="397.949" classname="com.tests.May27TestSuite4">
    <failure type="java.lang.AssertionError" message="myActiveOrder_SubmitOrder:Fail expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: myActiveOrder_SubmitOrder:Fail expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertFalse(Assert.java:63)
	at com.components.pages.MyActiveOrderPage.myActiveOrder_SubmitOrder(MyActiveOrderPage.java:195)
	at com.tests.May27TestSuite4.SubmitOrder_Categories_Search_Home(May27TestSuite4.java:130)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- SubmitOrder_Categories_Search_Home -->
  <testcase name="SubmitOrder_Categories_Search_Home" time="397.963" classname="com.tests.May27TestSuite4">
    <failure type="java.lang.RuntimeException" message="Error occured while closing webdriver sessionError communicating with the remote browser. It may have died.
Build info: version: &amp;apos;2.51.0&amp;apos;, revision: &amp;apos;1af067d&amp;apos;, time: &amp;apos;2016-02-05 19:15:17&amp;apos;
System info: host: &amp;apos;tvmatp2261m.ad.infosys.com&amp;apos;, ip: &amp;apos;10.155.162.81&amp;apos;, os.name: &amp;apos;Mac OS X&amp;apos;, os.arch: &amp;apos;x86_64&amp;apos;, os.version: &amp;apos;10.11&amp;apos;, java.version: &amp;apos;1.7.0_71&amp;apos;
Driver info: driver.version: RemoteWebDriver
Session ID: 73c62dfa-eccb-4611-8a74-2d697547e195
Capabilities [{automationName=Appium, platform=LINUX, app=/Users/jithya.joseph/Desktop/SyscoEndeca-debug.apk, javascriptEnabled=true, appActivity=, networkConnectionEnabled=true, desired={automationName=Appium, newCommandTimeout=120, app=/Users/jithya.joseph/Desktop/SyscoEndeca-debug.apk, platformVersion=6.0, autoWebview=false, deviceName=Sysco Galaxy S6, platformName=Android, appActivity=, appPackage=}, locationContextEnabled=false, appPackage=, newCommandTimeout=120, platformVersion=6.0.1, databaseEnabled=false, autoWebview=false, deviceName=1215fc6c214b2204, platformName=Android, webStorageEnabled=false, warnings={}, takesScreenshot=true}]">
      <![CDATA[java.lang.RuntimeException: Error occured while closing webdriver sessionError communicating with the remote browser. It may have died.
Build info: version: '2.51.0', revision: '1af067d', time: '2016-02-05 19:15:17'
System info: host: 'tvmatp2261m.ad.infosys.com', ip: '10.155.162.81', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11', java.version: '1.7.0_71'
Driver info: driver.version: RemoteWebDriver
Session ID: 73c62dfa-eccb-4611-8a74-2d697547e195
Capabilities [{automationName=Appium, platform=LINUX, app=/Users/jithya.joseph/Desktop/SyscoEndeca-debug.apk, javascriptEnabled=true, appActivity=, networkConnectionEnabled=true, desired={automationName=Appium, newCommandTimeout=120, app=/Users/jithya.joseph/Desktop/SyscoEndeca-debug.apk, platformVersion=6.0, autoWebview=false, deviceName=Sysco Galaxy S6, platformName=Android, appActivity=, appPackage=}, locationContextEnabled=false, appPackage=, newCommandTimeout=120, platformVersion=6.0.1, databaseEnabled=false, autoWebview=false, deviceName=1215fc6c214b2204, platformName=Android, webStorageEnabled=false, warnings={}, takesScreenshot=true}]
	at zRfghY.s.b(WebDriverFactory.java:48)
	at com.iwaf.framework.testng.TestNGTestListener.closeTestSession(TestNGTestListener.java:458)
	at com.iwaf.framework.testng.TestNGTestListener.onTestFailure(TestNGTestListener.java:291)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1693)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1677)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:702)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
Caused by: org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.
Build info: version: '2.51.0', revision: '1af067d', time: '2016-02-05 19:15:17'
System info: host: 'tvmatp2261m.ad.infosys.com', ip: '10.155.162.81', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11', java.version: '1.7.0_71'
Driver info: driver.version: RemoteWebDriver
Session ID: 73c62dfa-eccb-4611-8a74-2d697547e195
Capabilities [{automationName=Appium, platform=LINUX, app=/Users/jithya.joseph/Desktop/SyscoEndeca-debug.apk, javascriptEnabled=true, appActivity=, networkConnectionEnabled=true, desired={automationName=Appium, newCommandTimeout=120, app=/Users/jithya.joseph/Desktop/SyscoEndeca-debug.apk, platformVersion=6.0, autoWebview=false, deviceName=Sysco Galaxy S6, platformName=Android, appActivity=, appPackage=}, locationContextEnabled=false, appPackage=, newCommandTimeout=120, platformVersion=6.0.1, databaseEnabled=false, autoWebview=false, deviceName=1215fc6c214b2204, platformName=Android, webStorageEnabled=false, warnings={}, takesScreenshot=true}]
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:665)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:189)
	at org.openqa.selenium.remote.RemoteWebDriver.quit(RemoteWebDriver.java:526)
	at zRfghY.t.c(WebDriverInstanceGenerator.java:131)
	at zRfghY.s.b(WebDriverFactory.java:45)
	... 23 more
Caused by: org.openqa.selenium.WebDriverException: org.apache.http.conn.HttpHostConnectException: Connect to 10.155.162.81:4723 [/10.155.162.81] failed: Connection refused
Build info: version: '2.51.0', revision: '1af067d', time: '2016-02-05 19:15:17'
System info: host: 'tvmatp2261m.ad.infosys.com', ip: '10.155.162.81', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11', java.version: '1.7.0_71'
Driver info: driver.version: RemoteWebDriver
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:64)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:644)
	... 28 more
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to 10.155.162.81:4723 [/10.155.162.81] failed: Connection refused
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:151)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at org.openqa.selenium.remote.internal.ApacheHttpClient.fallBackExecute(ApacheHttpClient.java:144)
	at org.openqa.selenium.remote.internal.ApacheHttpClient.execute(ApacheHttpClient.java:90)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:52)
	... 29 more
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134)
	... 42 more
]]>
    </failure>
  </testcase> <!-- SubmitOrder_Categories_Search_Home -->
</testsuite> <!-- Default test -->
